package com.specificlanguages.mops.protocol

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.StructureKind
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.add
import kotlinx.serialization.json.addJsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray
import kotlinx.serialization.json.putJsonObject

/**
 * Emits the JSON Schema (draft 2020-12) for the edit-batch Notation, generated by walking the [EditBatch] serial
 * descriptors so it cannot drift from the wire format. The whole surface is a single [generate] returning the schema as
 * a string, so the CLI module consumes it through the thin protocol jar without touching serialization types.
 *
 * Three element types whose custom serializers hide their real wire shape — [EditTarget], [ChildPosition], and
 * [ModelDestination] — are the only hand-authored fragments (see [EDIT_TARGET_FRAGMENT], [CHILD_POSITION_FRAGMENT], and
 * [MODEL_DESTINATION_FRAGMENT]); they are spliced in wherever a field's element descriptor carries their serial name.
 */
@OptIn(ExperimentalSerializationApi::class)
object EditSchema {
    private const val EDIT_TARGET_SERIAL_NAME = "EditTarget"
    private const val CHILD_POSITION_SERIAL_NAME = "ChildPosition"
    private const val MODEL_DESTINATION_SERIAL_NAME = "ModelDestination"
    private const val INLINE_CHILD_SERIAL_NAME = "InlineChild"
    private const val INLINE_REFERENCE_SERIAL_NAME = "InlineReference"

    // The two hand-authored union fragments: EditTarget's custom serializer accepts a bare reference string (a node
    // reference or a $alias) or a {model, nodeId} object; ChildPosition's accepts the "first"/"last"/"only" keywords or
    // a bare integer index (deliberately not an {index: N} object).
    private val EDIT_TARGET_FRAGMENT: JsonObject = buildJsonObject {
        putJsonArray("anyOf") {
            addJsonObject { put("type", "string") }
            addJsonObject {
                put("type", "object")
                putJsonObject("properties") {
                    putJsonObject("model") { put("type", "string") }
                    putJsonObject("nodeId") { put("type", "string") }
                }
                putJsonArray("required") { add("model"); add("nodeId") }
                put("additionalProperties", false)
            }
        }
    }

    private val CHILD_POSITION_FRAGMENT: JsonObject = buildJsonObject {
        putJsonArray("anyOf") {
            addJsonObject {
                putJsonArray("enum") { add("first"); add("last"); add("only") }
            }
            addJsonObject { put("type", "integer") }
        }
    }

    // ModelDestination's custom serializer accepts a bare model target string (a serialized model reference, model name,
    // or file path) or a {model} object.
    private val MODEL_DESTINATION_FRAGMENT: JsonObject = buildJsonObject {
        putJsonArray("anyOf") {
            addJsonObject { put("type", "string") }
            addJsonObject {
                put("type", "object")
                putJsonObject("properties") {
                    putJsonObject("model") { put("type", "string") }
                }
                putJsonArray("required") { add("model") }
                put("additionalProperties", false)
            }
        }
    }

    /** The full edit-batch JSON Schema (draft 2020-12) as a pretty-printed string. */
    fun generate(): String {
        val defs = linkedMapOf<String, JsonObject>()

        val operationsContainer = EditBatch.serializer().descriptor
            .getElementDescriptor(0)
            .getElementDescriptor(0)
            .getElementDescriptor(1)

        val opSchemas = (0 until operationsContainer.elementsCount).map { i ->
            leafSchema(operationsContainer.getElementName(i), operationsContainer.getElementDescriptor(i), defs)
        }

        val root = buildJsonObject {
            put("\$schema", "https://json-schema.org/draft/2020-12/schema")
            put("title", "mops model edit batch")
            put("type", "object")
            putJsonObject("properties") {
                putJsonObject("operations") {
                    put("type", "array")
                    putJsonObject("items") {
                        put("oneOf", JsonArray(opSchemas))
                    }
                }
            }
            putJsonArray("required") { add("operations") }
            put("additionalProperties", false)
            if (defs.isNotEmpty()) {
                put("\$defs", JsonObject(defs))
            }
        }

        return prettyJson.encodeToString(JsonObject.serializer(), root)
    }

    // The `op` discriminator is synthetic (from @JsonClassDiscriminator), so it is not one of the leaf's own elements;
    // it is emitted here as a const and prepended to the required list.
    private fun leafSchema(op: String, leaf: SerialDescriptor, defs: MutableMap<String, JsonObject>): JsonObject =
        buildJsonObject {
            put("type", "object")
            putJsonObject("properties") {
                putJsonObject("op") { put("const", op) }
                for (i in 0 until leaf.elementsCount) {
                    put(leaf.getElementName(i), fieldSchema(leaf.getElementDescriptor(i), defs))
                }
            }
            putJsonArray("required") {
                add("op")
                for (i in 0 until leaf.elementsCount) {
                    if (!leaf.isElementOptional(i)) add(leaf.getElementName(i))
                }
            }
            put("additionalProperties", false)
        }

    private fun fieldSchema(descriptor: SerialDescriptor, defs: MutableMap<String, JsonObject>): JsonObject {
        val base = schemaFor(descriptor, defs)
        return if (descriptor.isNullable) nullable(base) else base
    }

    private fun schemaFor(descriptor: SerialDescriptor, defs: MutableMap<String, JsonObject>): JsonObject {
        // Special-case the two custom-serializer types before inspecting the kind: their descriptors do not describe
        // their real wire shape (EditTarget reports an empty object, ChildPosition reports a plain string). A nullable
        // field's descriptor carries a trailing "?" in its serial name, so compare against the non-nullable name.
        when (descriptor.serialName.removeSuffix("?")) {
            EDIT_TARGET_SERIAL_NAME -> return EDIT_TARGET_FRAGMENT
            CHILD_POSITION_SERIAL_NAME -> return CHILD_POSITION_FRAGMENT
            MODEL_DESTINATION_SERIAL_NAME -> return MODEL_DESTINATION_FRAGMENT
            INLINE_CHILD_SERIAL_NAME -> return inlineChildFragment(defs)
            INLINE_REFERENCE_SERIAL_NAME -> return inlineReferenceFragment(defs)
        }

        return when (descriptor.kind) {
            PrimitiveKind.STRING, PrimitiveKind.CHAR -> typeObject("string")
            PrimitiveKind.BOOLEAN -> typeObject("boolean")
            PrimitiveKind.BYTE, PrimitiveKind.SHORT, PrimitiveKind.INT, PrimitiveKind.LONG -> typeObject("integer")
            PrimitiveKind.FLOAT, PrimitiveKind.DOUBLE -> typeObject("number")
            StructureKind.LIST -> buildJsonObject {
                put("type", "array")
                put("items", fieldSchema(descriptor.getElementDescriptor(0), defs))
            }
            StructureKind.CLASS, StructureKind.OBJECT -> objectRef(descriptor, defs)
            else -> JsonObject(emptyMap())
        }
    }

    // Reusable object types (e.g. the recursive node subtree) are emitted once into $defs and referenced, so a type that
    // contains itself does not recurse forever.
    private fun objectRef(descriptor: SerialDescriptor, defs: MutableMap<String, JsonObject>): JsonObject {
        val name = descriptor.serialName.substringAfterLast('.')
        if (name !in defs) {
            defs[name] = JsonObject(emptyMap())
            defs[name] = buildJsonObject {
                put("type", "object")
                putJsonObject("properties") {
                    for (i in 0 until descriptor.elementsCount) {
                        put(descriptor.getElementName(i), fieldSchema(descriptor.getElementDescriptor(i), defs))
                    }
                }
                putJsonArray("required") {
                    for (i in 0 until descriptor.elementsCount) {
                        if (!descriptor.isElementOptional(i)) add(descriptor.getElementName(i))
                    }
                }
                put("additionalProperties", false)
            }
        }
        return buildJsonObject { put("\$ref", "#/\$defs/$name") }
    }

    // A child position in an Inline Subtree: a fresh-node spec, a {role?, move} leaf, or a {role?, copy} leaf. The
    // custom serializer hides this union, so it is hand-authored; the fresh branch forces the InlineNode object into
    // $defs and references it.
    private fun inlineChildFragment(defs: MutableMap<String, JsonObject>): JsonObject {
        val freshRef = objectRef(InlineNode.serializer().descriptor, defs)
        return buildJsonObject {
            putJsonArray("anyOf") {
                add(freshRef)
                add(leafBranch("move"))
                add(leafBranch("copy"))
            }
        }
    }

    private fun leafBranch(leaf: String): JsonObject = buildJsonObject {
        put("type", "object")
        putJsonObject("properties") {
            putJsonObject("role") { put("type", "string") }
            put(leaf, EDIT_TARGET_FRAGMENT)
        }
        putJsonArray("required") { add(leaf) }
        put("additionalProperties", false)
    }

    // An inline Reference: {role, to} (the EditTarget grammar) or {role, target} (the get-node-shaped object). The
    // custom serializer hides this shape, so it is hand-authored; the target branch references the get-node target def.
    private fun inlineReferenceFragment(defs: MutableMap<String, JsonObject>): JsonObject {
        val targetRef = objectRef(MpsNodeReferenceTargetJson.serializer().descriptor, defs)
        return buildJsonObject {
            put("type", "object")
            putJsonObject("properties") {
                putJsonObject("role") { put("type", "string") }
                put("to", EDIT_TARGET_FRAGMENT)
                put("target", targetRef)
            }
            putJsonArray("required") { add("role") }
            put("additionalProperties", false)
        }
    }

    private fun typeObject(type: String): JsonObject = buildJsonObject { put("type", type) }

    private fun nullable(base: JsonObject): JsonObject = buildJsonObject {
        putJsonArray("anyOf") {
            add(base)
            addJsonObject { put("type", "null") }
        }
    }

    private val prettyJson = Json { prettyPrint = true }
}
