[
    'list-project-modules': [
        group: 'commands',
        title: 'List project modules',
        kind: 'cli',
        code: '''mops list''',
    ],
    'include-platform-library-modules': [
        group: 'commands',
        title: 'Include platform/library modules',
        kind: 'cli',
        code: '''mops list /''',
    ],
    'list-a-module-s-models': [
        group: 'commands',
        title: 'List a module\'s models',
        kind: 'cli',
        code: '''mops list sample.solution''',
    ],
    'list-model-roots': [
        group: 'commands',
        title: 'List model roots',
        kind: 'cli',
        code: '''mops list sample.solution .main''',
    ],
    'inspect-a-root-and-its-children': [
        group: 'commands',
        title: 'Inspect a root and its children',
        kind: 'cli',
        code: '''mops list sample.solution .main Example --depth 2''',
    ],
    'inspect-a-node-using-its-stable-reference': [
        group: 'commands',
        title: 'Inspect a node using its stable reference',
        kind: 'cli',
        code: '''mops list 'NODE_REF' --depth 2''',
    ],
    'show-all-children-without-truncation': [
        group: 'commands',
        title: 'Show all children without truncation',
        kind: 'cli',
        code: '''mops list 'NODE_REF' --limit 0''',
    ],
    'count-child-roles-concepts': [
        group: 'commands',
        title: 'Count child roles/concepts',
        kind: 'cli',
        code: '''mops list 'NODE_REF' --summary''',
    ],
    'list-one-containment-role': [
        group: 'commands',
        title: 'List one containment role',
        kind: 'cli',
        code: '''mops list 'NODE_REF' --role member''',
    ],
    'export-a-node-subtree-as-json': [
        group: 'commands',
        title: 'Export a node subtree as JSON',
        kind: 'cli',
        code: '''mops get node 'NODE_REF'''',
    ],
    'include-its-ancestry': [
        group: 'commands',
        title: 'Include its ancestry',
        kind: 'cli',
        code: '''mops get node --ancestry 'NODE_REF'''',
    ],
    'resolve-an-id-within-a-model': [
        group: 'commands',
        title: 'Resolve an ID within a model',
        kind: 'cli',
        code: '''mops get node sample.model 123456789''',
    ],
    'read-the-default-editor-s-text': [
        group: 'commands',
        title: 'Read the default editor\'s text',
        kind: 'cli',
        code: '''mops render node 'NODE_REF'''',
    ],
    'render-with-unloaded-languages': [
        group: 'commands',
        title: 'Render with unloaded languages',
        kind: 'cli',
        code: '''mops render node --allow-reflective 'NODE_REF'''',
    ],
    'emit-clickable-mps-urls-in-text-output': [
        group: 'commands',
        title: 'Emit clickable MPS URLs in text output',
        kind: 'cli',
        code: '''mops --refs-as-urls list sample.solution .main''',
    ],
]
